# Generated by Django 2.0 on 2022-05-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190703_0259'),
    ]

    operations = [
    ]
