# Generated by Django 2.0 on 2022-05-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20220512_1029'),
    ]

    operations = [
    ]
